### ISSUE TITLE
Computer Vision Projects with Gradio Section

### ISSUE THREAD

**Issue by alperenunlu** [johko/computer-vision-course#20]
Hello everyone, 👋🏻 

Let's outline the section on hands on interactive projects with gradio.

Topics Draft
- [ ] Intro to using Gradio.
- [ ] Using Gradio Interface class and 🤗 Transformers API integration.
- [ ] Using Gradio Blocks API.
- [ ] Gradio CV specific Components.
- [ ] Gradio CV projects.
    - Gradio CV project(Detection, Segmentation, Generating etc.) [1 ... N].

There should be more projects based on the content of other sections.

Before finalizing let's gather thoughts and discuss.

**Comment by johko** [comment]
Thanks for bringing this up. Basically this is your proposal to add a new section to the course, which covers how to build demos with gradio right?

I like the idea in general, but I guess it needs a lot of communication with the other teams, to figure out which demos to build. This would probably be easier once the other section are complete.

What do you think @merveenoyan and @lunarflu ?

**Comment by ash-01xor** [comment]
I would also like to know if we are treating this as a separate section of the book or do we let this be a part of each team.

As in , as each team collaborates and  writes a notebook regarding the particular chapter, i feel it would be better if the team itself can collaborate and come up with a small gradio application for the topic.

In such a case , certain topics wouldn't need gradio applications yet the ones which need will atleast be thought out and be uniform.

What do you all think?

**Comment by lunarflu** [comment]
Good initiative @alperenunlu !
> it needs a lot of communication with the other teams, to figure out which demos to build. This would probably be easier once the other section are complete.

Agreed here, there seems to be a lot of overlap with other sections (i.e. should a demo go under `Gradio` or `CNNs`, etc). Could be nice to have a quick intro maybe somewhere down the line once we flesh out the rest of the content a bit.

**Comment by ash-01xor** [comment]
> It can be written by that topics team also it can be written after by a different team when section is more or less complete

Well that makes sense , making this course hands on as you say will benefit people getting a more hands on approach.
Since i have experience working on segmentation problems before , can i be assigned to create the image segmentation project ?

**Comment by alperenunlu** [comment]
Yes that is better actually. Where we should put gradio section begining, in the middle, or end?

I am thinking like after CNN would be better it's relatively at the begining and enough knowledge to projects with gradio.

**Comment by lunarflu** [comment]
>Where we should put gradio section begining, in the middle, or end?

I think beginning is fine like @merveenoyan said, give a quick intro to a few key components then move straight into a few demos using them. What do you think?

**Comment by alperenunlu** [comment]
> >Where we should put gradio section begining, in the middle, or end?
> 
> @alperenunlu I think beginning is fine like @merveenoyan said, give a quick intro to a few key components then move straight into a few demos using them. What do you think?

I edited the suggested chapters on the top of the page according to that suggestion from @merveenoyan . Merve's suggestion was great if we would want to increase demos we can do it later.

**Comment by alperenunlu** [comment]
> Topics Draft
> - [ ] Intro to using Gradio.
> - [ ] Using Gradio Interface class and 🤗 Transformers API integration.
> - [ ] Using Gradio Blocks API.
> - [ ] Gradio CV specific Components.
> - [ ] Gradio CV projects.
>     - Gradio CV project(Detection, Segmentation, Generating etc.) [1 ... N].


New suggested topics is this what do you think @merveenoyan @lunarflu .

**Comment by merveenoyan** [comment]
@alperenunlu I think the new outline works :)
