### ISSUE TITLE
[Spreadsheet] Access Denied

### ISSUE THREAD

**Issue by lunarflu** [johko/computer-vision-course#22]
<img width="480" alt="image" src="https://github.com/johko/computer-vision-course/assets/70143200/7fb574cd-4742-4708-bc56-88323c533a7b">

This link doesn't seem to work https://docs.google.com/spreadsheets/d/1fjmbsdGwe7IUMBv74LDC7IpoJy8ijiFdzGdnDlBv6eA/edit#gid=0

Linked to here and here I believe

<img width="593" alt="image" src="https://github.com/johko/computer-vision-course/assets/70143200/0db8ed6b-79e8-41b1-9de2-d49726755cbe">
<img width="320" alt="image" src="https://github.com/johko/computer-vision-course/assets/70143200/37a1dc20-4f91-4b89-afd7-949807c382b6">

**Comment by johko** [comment]
Solved it by reshariing
