### ISSUE TITLE
Latex and <Tip> blocks seems to not render correctly 

### ISSUE THREAD

**Issue by lulmer** [johko/computer-vision-course#222]
**Description:**
While accessing the preliminary rendered content of the "Welcome" unit in the computer vision course hosted at [this link](https://moon-ci-docs.huggingface.co/docs/computer-vision-course/pr_212/en/Unit%200%20-%20Welcome/welcome), @bellabf and I encountered two main issues that significantly impact the readability and educational value of the material.

1. **LaTeX Equations Not Displaying Correctly:** The LaTeX equations embedded within the course content are not rendered properly. It appears that equations enclosed in single dollar signs `$...$` or  `$$...$$` do not show up as expected. I'm not sure if the problem lies with the Markdown renderer or another aspect of the documentation infrastructure.

2. **`<Tip>` Block Quotes Not Visible:** Additionally, the custom `<Tip>...</Tip>` block quotes intended to highlight important information or tips are not visible at all. This makes it difficult to distinguish essential pointers or notes that could enhance understanding of the course material.

**Questions:**
- Has anyone else encountered these issues, or is it an isolated case specific to the viewing website ?
- Are there any known fixes or workarounds for the LaTeX equation rendering problem? Specifically, does switching to double dollar signs `$$...$$` consistently resolve similar issues?
- Regarding the `<Tip>` block quotes not showing up, is this a known limitation of the current "beta" documentation platform, or could it be an oversight in the HTML/CSS styling?

**Possible Solutions:**
- For the `<Tip>` block quotes, it might be worthwhile to review the CSS associated with these elements or ensure that the custom HTML tags are correctly interpreted by the Markdown renderer.

**Request:**
We are reaching out to the documentation team and the course maintainers to seek guidance on these issues. 

**Example:**
Here is a screenshot I took for one of the affected chapters (Unit13: Hyena). Unit 1: Images, Unit13: Hiera, and I suppose all the chapters that have equations/tips are also affected :
![image](https://github.com/johko/computer-vision-course/assets/36041351/be51bb52-d5da-41a7-9a5f-234cfc567d7b)

**Comment by bellabf** [comment]
I believe this was solved by https://github.com/johko/computer-vision-course/pull/228, https://github.com/johko/computer-vision-course/pull/220 and others. The other problem with the spaces comes from the docbuilder (https://github.com/johko/computer-vision-course/pull/228#issuecomment-2006591074) 

Maybe we can close this @johko?

**Comment by lulmer** [comment]
@bellabf indeed it has been fixed ! I close it
