### ISSUE TITLE
Should we use safetensors?

### ISSUE THREAD

**Issue by johko** [johko/computer-vision-course#25]
I wondered if we should add an official recommendation to use the `safetensors` saving format wherever possible.

But I have to admit, that I'm not that familiar with it, so I don't know how much overhead it would be in cases where we cannot use a HF library like `transformers`.

**Comment by merveenoyan** [comment]
@johko I think it's fine, I don't have any strong opinion 😊

**Comment by johko** [comment]
ok, I guess it is also not that important for now. We'll just stick to whatever people use for now to keep complexity low
