### ISSUE TITLE
Selecting Frameworks and Implementing a MultiFramework Approach for the Course

### ISSUE THREAD

**Issue by alperenunlu** [johko/computer-vision-course#26]
## Framework Choice

To create a comprehensive course, we must select and commit to specific frameworks. I propose focusing on [PyTorch](http://pytorch.org/) and [Jax](https://jax.readthedocs.io/en/latest/#) due to their popularity and versatile applications.

## MultiFramework Vs MonoFramework Approach

Consider using two or more frameworks for each lesson, providing both Jax and PyTorch code options. This enables learners to choose their preferred framework and facilitates Jax adoption for those already familiar with PyTorch.

---

Let's collect suggestions and insights on this matter.

**Comment by adhiiisetiawan** [comment]
Yess, I agree to focus on PyTorch and Jax

**Comment by wonhyeongseo** [comment]
+1. Also we can focus on PyTorch first, then expand to JAX and TensorFlow like in the [transformers docs](https://huggingface.co/docs/transformers/tasks/language_modeling#train).

**Comment by merveenoyan** [comment]
I think JAX is not as popular as TensorFlow (you can check out pip install stats). 
https://pypistats.org/packages/jax

**Comment by johko** [comment]
I also agree that we should focus on one framework (PyTorch) for now and make sure we get high quality content with that.
