### ISSUE TITLE
A view synthesis chapter?

### ISSUE THREAD

**Issue by mmhamdy** [johko/computer-vision-course#27]
Hi 👋
I think the chapter about 3D vision is quite overloaded. I suggest dedicating a separate chapter for view synthesis to do both topics justice.

For example (just a suggestion), the content of the two chapters could look like this:

### 3D Computer Vision:
- [ ] 3D Object Detection
- [ ] 3D Human Pose Estimation
- [ ] Point Cloud Classification
- [ ] 3D Object Tracking

### View Synthesis:
- [ ] Scene Reconstruction
- [ ] NeRF 
- [ ] Gaussian Splatting

**Comment by sitloboi2012** [comment]
You could try with YOLOv8 Pose Model from Ultralytics they are pretty good. Just a comment :)

**Comment by julien-blanchon** [comment]
Yes I agree it's a little bit overloaded. Both part share many concept and I don't know if view synthesis could be read without some aspect of the 3d computer vision (obviously the inverse is possible). I think this may decide if we can split the chapter in two.

**Comment by julien-blanchon** [comment]
You have a suggestion of TOC here by @\cywiz57 on the 3D Vision thread: https://docs.google.com/document/d/12nkX_y8e0Az3rTjKUXm9UwwckiS8VMoeAbiIX6puOCQ/edit#heading=h.mx0ta5109jwy

**Comment by mmhamdy** [comment]
Wow! Amazing work! I agree with you, @julien-blanchon, that many concepts in 3D vision pave the way for understanding view synthesis. But this will make the chapter way too long compared to other courses. I mean, you can have a whole book about NeRF alone! 😅. My suggestion for separation was to give both topics their deserved space. As for concept dependence, I think we could assume some dependence between chapters in the same section.

**Comment by johko** [comment]
I do think it makes sense to keep them both together, especially with the new course structure where we have a separate notebooks folder, maybe you can combine some topics for the theoretical part and give more detail in a notebook.

**Comment by mmhamdy** [comment]
Agree, having two spaces for theory and practice can compensate. I understand the need to not stretch the course materials.
