### ISSUE TITLE
Missing video link in CNN Unit

### ISSUE THREAD

**Issue by sergiopaniego** [johko/computer-vision-course#281]
In Unit 2 - Introduction to Convolutional Neural Networks, in section [Convolutional Neural Networks](https://huggingface.co/learn/computer-vision-course/unit2/cnns/introduction#convolutional-neural-networks) it reads: ` We’d like you to watch this video to gain a better intuition` but no link is provided. Should we remove that sentence?

**Comment by bellabf** [comment]
I think it was @merveenoyan that wrote it.  Maybe she can give the link and we can fix it? Otherwise, I would say it is better to remove it.

**Comment by kudosscience** [comment]
@sergiopaniego I also noticed that while reading the course for the first time today.

**Comment by sezan92** [comment]
@sergiopaniego would you like to remove the line? if yes, feel free to open PR

**Comment by sergiopaniego** [comment]
Sure @sezan92, I'll generate the PR removing it so the content is more cleaner 😄
