### ISSUE TITLE
Definition of image

### ISSUE THREAD

**Issue by frankl1** [johko/computer-vision-course#297]
Hi,

I am starting the course and I have just joined the community on Discord. There might be a typo in the definition of an image in Unit 1.

<img width="596" alt="image" src="https://github.com/johko/computer-vision-course/assets/23366578/0a1dbb82-22ec-4829-9839-5855be1a6681">

Shouldn't it be $n=2$ and not $n=1$ ?

Thanks

**Comment by seshupavan** [comment]
@bellabf

**Comment by bellabf** [comment]
Thanks @frankl1 and thanks @seshupavan. I open a PR to fix it.

**Comment by frankl1** [comment]
Awesome
