### ISSUE TITLE
Unit 4 Transfer Learning Application Notebook Links 

### ISSUE THREAD

**Issue by ThatOrJohn** [johko/computer-vision-course#302]
https://github.com/johko/computer-vision-course/blob/main/chapters/en/unit4/multimodal-models/transfer_learning.mdx

The notebook links in the Transfer Learning Application section don't go anywhere.

e.g.,

`[CLIP notebook](https://)`

**Comment by ThatOrJohn** [comment]
fwiw, it looks like this might be the CLIP fine-tuning notebook, but not seeing any candidates for the others.

https://github.com/johko/computer-vision-course/blob/f2fa020c0fbadec42b2fb95d9cce77f303aceaae/notebooks/Unit%204%20-%20Multimodal%20Models/Clip_finetune.ipynb

**Comment by minemile** [comment]
Hello! Thanks for highlighting the problem. I'll fix the links soon.

Unfortunately, notebooks for other models except the CLIP model are not ready.

**Comment by bellabf** [comment]
I might be enough to open a PR changing the link to "Coming Soon" now and then correct the link once the notebooks are ready.

**Comment by minemile** [comment]
@bellabf Certainly! But in order to have at least some examples of fine-tuning, I added links from open sources.

**Comment by sezan92** [comment]
this issue should be closed
