### ISSUE TITLE
Typographical Error in Unit 1, ‘Definition of Image’ section

### ISSUE THREAD

**Issue by achrafib1** [johko/computer-vision-course#309]
In the in Unit 1, ‘Definition of Image’ section, there is a statement that says, “More precisely, an image is an n-dimensional function. We will first consider it to be two-dimensional where **n=1**.” However, for a two-dimensional image, n should be equal to 2. This appears to be a typographical error that could cause confusion for readers. I propose correcting this statement to: “More precisely, an image is an n-dimensional function. We will first consider it to be two-dimensional where **n=2**"

**Comment by bellabf** [comment]
Hi, this was already mentioned in another issue https://github.com/johko/computer-vision-course/issues/297. I have opened a PR to fix it, but it has not been merged yet https://github.com/johko/computer-vision-course/pull/301. Thank you so much for pointing this out, I am hoping to get this fixed soon :).

**Comment by achrafib1** [comment]
Great, I appreciate the update. Thank you for your efforts! 👍

**Comment by sezan92** [comment]
this issue should be closed

**Comment by achrafib1** [comment]
Thank you for the update, I am closing it now.
