### ISSUE TITLE
Unit 3 - Vision Transformer: Transfer learning notebook dataset loads without decoding the images.

### ISSUE THREAD

**Issue by benjamin-printify** [johko/computer-vision-course#311]
The [notebook](https://github.com/johko/computer-vision-course/blob/main/notebooks/Unit%203%20-%20Vision%20Transformers/transfer-learning-image-classification.ipynb) expects a PIL image under each data point's `'image'` key, but it actually loads a dict with `'path'` and `'bytes'` (the dataset is not decoded). This makes the notebook fail, starting from the cell in which some images are displayed.

Not sure this is the right solution but, by explicitly doing the decoding when loading the dataset solves it:

```python
dataset = load_dataset('pcuenq/oxford-pets').cast_column('image', Image(decode=True))
```

(importing `Image` from `datasets`).

**Comment by kawchar85** [comment]
https://github.com/johko/computer-vision-course/issues/312#issuecomment-2294832966
