### ISSUE TITLE
transfer-learning-image-classification.ipynb error

### ISSUE THREAD

**Issue by maaxlong** [johko/computer-vision-course#312]
I'm getting an error when running this Colab notebook. When I run the cell dataset['train'][0], the 'image' field is a long list of bytes. I think this is the cause of the following error that I get when I run the succeeding cell: 'TypeError: Image data of dtype object cannot be converted to float'. Any suggestions?

**Comment by kawchar85** [comment]
In **show_samples** function, replace the line `img = samples[i]['image']` by
 `img_bytes = samples[i]['image']['bytes']
   img = Image.open(io.BytesIO(img_bytes))`

In **transforms** function, replace the line `batch['image'] = [x.convert('RGB') for x in batch['image']]` by
`batch['image'] = [Image.open(io.BytesIO(x['bytes'])).convert('RGB') for x in batch['image']]`
@maaxlong
