### ISSUE TITLE
Common Pre-Trained Models (ResNet, etc.) Discussion

### ISSUE THREAD

**Issue by sezan92** [johko/computer-vision-course#39]
Hello. This issue is for discussion about the chapter Common Pre-Trained Models

# My thoughts

In the following paragraphs, I am adding my thoughts. This will be finalized after discussion.

## What do you think should be added?

The chapter assumes the reader nows fairly about the CNN algorithms. Now are job is to address the major architectures using CNN. 

### Architectures to be added

- Vgg16/19 (First deep CNN)
- Resnet (Residual net helped )
- Googlenet (inception model)
- Resnext
- Convnext

### How would you like to explain?

- I think the chapter should be diagram-heavy and if possible some implementations of the architectures.

Please let me know your thoughts

**Comment by ATaylorAerospace** [comment]
Hello! If the different layers of CNN's are covered in an earlier chapter, I think a short refresher review of Convolutional, Pooling and Fully connected layers might be a great start to this chapter before the deep dive into the various CNN architectures.

**Comment by ash-01xor** [comment]
Hey @ATaylorAerospace ,

> If the different layers of CNN's are covered in an earlier chapter, I think a short refresher review of Convolutional, Pooling and Fully connected layers might be a great start to this chapter before the deep dive into the various CNN architectures.

My team is dealing with the general architechture and we would be taking care of all these details , we are yet to finalize on the final content as of now , after which we will release the issue for comments.

This chapter in specific deals with only common pre-trained models .

Thanks

**Comment by johko** [comment]
Thank you for the outline @sezan92 :slightly_smiling_face: 

> Architectures to be added
Lenet ( first CNN)
Alexnet (First one to use GPU)
Vgg16/19 (First deep CNN)
Resnet (Residual net helped )
Google (inception model)
Mobilenet (first optimized for mobile devices)

I like the historical approach, starting from LeNet and then going further. But for my liking it still fells a bit "too old". I like reflecting on where we come from, but I think the people might also want to know what "modern" CNNs are there, because it is not all about ViTs these days. For this I think you should also **add ConvNext** (https://github.com/facebookresearch/ConvNeXt) as it is a good representative of current SOTA CNNs

> I think the chapter should be diagram-heavy and if possible some implementations of the architectures.

Makes sense for architectures, even nicer would be animations, but I don't know how well that works within .mdx files.

**Comment by sezan92** [comment]
@johko thank you for your reply, I am adding Convnext then . I thought SOTA architectures would be added in the last chapter (modern architectures)


I have a question, how do you think we should proceed about hands-on approach?

**Comment by socd06** [comment]
+1 for the diagrams. I would suggest making these lessons more practical and keeping only the top maybe 5 most popular CNNs as per their usage in HF with small demos for each, explaining their common use cases. Then they could segway into the transfer learning/fine tuning lessons.

**Comment by alperenunlu** [comment]
> I think they don't have an outline yet, but maybe @alperenunlu or someone else from the team can already give some info.

@johko I just write myself in the first chapter. I will look into this.

**Comment by alperenunlu** [comment]
> ### Architectures to be added
> 
> - Lenet ( first CNN)
> - Alexnet (First one to use GPU)
> - Vgg16/19 (First deep CNN)
> - Resnet (Residual net helped )
> - Google (inception model)
> - Mobilenet (first optimized for mobile devices)


By the way some things and mistakes about this list.

LeNet-5 would be more suitable (of course with different last layers)

Alexnet is not the first to use GPU. It's importance is more complex but showed that CNN's can be powerful by winning imagenet.

The name of the architecture is not Google it's GoogLeNet.

**Comment by merveenoyan** [comment]
Hello 👋 I agree with @johko on not including old ones. Except for that it sounds good.

**Comment by ShamieCC** [comment]
Hello I just joined the team today, we could also show code implementations of these models to show practical use cases?

**Comment by sezan92** [comment]
i have a question for @johko @merveenoyan , what about the implementations? As it is my first time, do we need to implement from scratch (using some framework), or do we show some use cases from model zoos? 

I prefer to implement it from scratch. I need to know others' opinions.

**Comment by sezan92** [comment]
> Hello I just joined the team today, we could also show code implementations of these models to show practical use cases?

i have some confusion regarding the implementation

**Comment by sezan92** [comment]
> Hello I just joined the team today, we could also show code implementations of these models to show practical use cases.

@ShamieCC I have asked pinged you in Discord server. please check

**Comment by sezan92** [comment]
I think the best would be 

- Vgg16/19 
- Resnet 
- Googlenet
- Resnext
- Convnext 

Each of the architecture is kind of new milestone for CNN. 

what do you guys think? @johko @merveenoyan @alperenunlu

**Comment by johko** [comment]
Sorry for the late reply @sezan92 , I kinda missed it. I think the proposal is good to start with.

**Comment by Mkrolick** [comment]
Hey 👋, just wanted to add a follow up question if anyone is working on explaining MobileNet. As that a key component of that paper (MobileNetv2 blocks), is used for an architecture in the common vision transformers section that I am writing.

**Comment by Mkrolick** [comment]
@sezan92 Sorry for not responding back! That sounds great. I can also add it in after the sprint if you'd like.
