### ISSUE TITLE
Zero-shot Computer Vision - Draft Outline

### ISSUE THREAD

**Issue by mmhamdy** [johko/computer-vision-course#43]
This is an early draft outlining the Zero-shot Computer Vision chapter. Below I'll give a brief overview of the chapter content.
There is also a [presentation slides](https://drive.google.com/file/d/1VUU6nP7QkZpRuoMgiUAVqcg-CCyNs4o0/view?usp=share_link) for the main concepts with some (little😃) details available.

### 🔹 Introduction
This section will basically lay the ground for the rest of the chapter. Each subsection was initially a section of its own, but then we thought that it would be better to merge them together under one heading.

- [x] **On Generalization**
- [x] **Zero-shot Learning (ZSL), History and Definitions**
- [x] **Comparison With Other Techniques**: This part aims to differentiate between zero-shot learning and some other methods such as [Open Set Recognition (OSR)](https://paperswithcode.com/task/open-set-learning), [Domain Adaptation](https://paperswithcode.com/task/domain-adaptation), and [Out of Distribution (OOD) Detection](https://paperswithcode.com/task/ood-detection)
- [x] **Relationship with Transfer Learning**: This part discusses how is zero-shot learning related to transfer learning, and differentiates between homogeneous and heterogeneous transfer learning. this will only discuss parts related to ZSL as there is already a transfer learning chapter.

### 🔹 Side Box: How Humans Recognize New Objects
This is a collapsable box for the interested reader about how humans are good at identifying new unseen objects and why this is not the same for machines.

### 🔹 Zero-shot Learning methods

- [ ] **Attributes and Descriptors**: Discusses what are attributes and why the a need for them in ZSL. 
- [ ] **Visual and Semantic Spaces**: Discusses different embedding spaces for the visual and semantic data.
- [ ] **ZSL Baselines**: Discusses the [Directed Attribute Prediction (DAP) algorithm](https://ieeexplore.ieee.org/abstract/document/6571196/) as a baseline for ZSL.
- [ ] **ZSL Algorithms**: Discusses some selected zero-shot learning algorithms such as [Embarrassingly Simple Zero-Shot Learning (ESZSL)](https://proceedings.mlr.press/v37/romera-paredes15.pdf), [Deep Visual-Semantic Embedding (DeViSE)](https://papers.nips.cc/paper_files/paper/2013/hash/7cce53cf90577442771720a370c3c723-Abstract.html), [Attribute Label Embedding (ALE)](https://arxiv.org/abs/1503.08677), [Structured Joint Embedding (SJE)](https://arxiv.org/abs/1409.8403), [and Semantic Autoencoder (SAE)](https://arxiv.org/abs/1704.08345)
- [ ] **ZSL Benchmarks**: Dicusses some ZSL benchmarks such as [Animals with Attributes2 (AWA2)](https://paperswithcode.com/dataset/awa2-1), [Caltech-UCSDBirds 200-2011 (CUB)](https://paperswithcode.com/dataset/cub-200-2011), [Attribute Pascal and Yahoo (aPY)](https://paperswithcode.com/dataset/apy), and [Sun attribute database (SUN)](https://paperswithcode.com/dataset/sun-attribute).
- [ ] **Evaluation**: How zero-shot learning is evaluated, and the [ZSLGBU Framework](https://arxiv.org/abs/1707.00600)
- [ ] **ZSL vs. Generalized ZSL**: What is Generalized Zero-shot Learning (GZSL), and how it is a more realistic version of plain zero-shot learning?

### 🔹 Zero-shot Learning with CLIP and friends
- [ ] **How is CLIP Different From Previous Approaches**: [CLIP](https://arxiv.org/abs/2103.00020) has been introduced in previous chapters. Here, we will discuss briefly (I hope) the parts related to zero-shot learning.

### 🔹 Zero-shot Learning in Computer Vision
This part illustrates how zero-shot learning can be used in the context of many different computer vision tasks. CV tasks were introduced in previous chapters.

#### Zero-shot Object Recognition/ Image Classification
- [ ] Methods
- [ ] Code Example

#### Zero-shot Object Detection
- [ ] Methods
- [ ] Code Example

#### Zero-shot Instance Segmentation
- [ ] Methods
- [ ] Code Example

#### Other CV Tasks
Besides the three most common CV tasks mentioned above, in this section, we may discuss other interesting CV tasks in the ZSL context.

### 🔹 Advantages of Zero-shot Learning
This section discusses why zero-shot learning is important. This will span a paragraph or two at most.

### 🔹 Applications of Zero-shot Learning
This section aims to provide some real-world applications of zero-shot learning in a computer vision context. There are no specific ones yet. 

### 🔹 Challenges and Limitations of Zero-shot Learning

- [ ] Bias
- [ ] Domain Shift
- [ ] Hubness
- [ ] Semantic Loss

### 🔹 Frontiers
This is a paragraph or a little bit more mentioning the current state-of-the-art and or recent experimental approaches in zero-shot learning. 

### 🔹 Chapter Summary
This is another paragraph (or two 😅) that aims to condense the main ideas discussed in the chapter and Key Takeaways.

### 👩‍💻 Hands-on Notebook
This is a hands-on notebook that shows two things: 
1. The implementation of a classic ZSL algorithm, for example, [ESZSL](https://proceedings.mlr.press/v37/romera-paredes15.pdf) from scratch.
2. The implementation of a ZSL pipeline using CLIP or another friend from scratch.

---

**Notes**
1. The chapter contents may seem overwhelming but we hope that we will get to a much shorter and dense version when we start working on the details.
2. The Algorithms part is the most volatile (high probability of change) one. There are a lot of ZSL algorithms out there and we are trying to choose a representative sample showing different approaches.
3.  We will make sure that the ratio of plain ZSL : CV ZSL remains in the reasonable range.

**Other Resources**:
- [Zero-Shot Category-Level Object Pose Estimation](https://arxiv.org/abs/2204.03635)
- [Large-Scale Zero-Shot Image Classification from Rich and Diverse Textual Descriptions](https://arxiv.org/abs/2103.09669)

**Comment by ATaylorAerospace** [comment]
This looks to be a great chapter and has an incredible amount of content! :-)

On the Notebook for the chapter. Since a generalized ZSL will be included (ESZSL) in the notebook,should you also include a more robust example for TOP-1 accuracy like SOMZSL, TGMZ or Cosmo?. That way the students can work thru a simple linear model with ESZSL but also get to work with methods that are more accurate.

**Comment by alperenunlu** [comment]
Comprehensive content. This is just terrific.

Looking forward to this.
🚀 🚀 🚀 🚀 🚀

**Comment by mmhamdy** [comment]
> This looks to be a great chapter and has an incredible amount of content! :-)
> 
> On the Notebook for the chapter. ...since a generalized ZSL will be included (ESZSL) in the notebook,should you also include a more robust example for TOP-1 accuracy like SOMZSL, TGMZ or Cosmo?. That way the students can work thru a simple linear example with ESZSL but also get to work with methods that are more accurate.

Thanks, @ATaylorAerospace. We're still not sure which algorithm to use in the notebook but surely will keep that in mind.

**Comment by mmhamdy** [comment]
> Comprehensive content. This is just terrific.
> 
> Looking forward to this. 🚀 🚀 🚀 🚀 🚀

Thanks, @alperenunlu for taking the time to read it.

**Comment by lunarflu** [comment]
Looks awesome! My guess is for a first try we want to shorten a bit + condense, and then in followups we can go more indepth (could be faster to iterate that way and not get hung up releasing everything completed)

What do you think?

**Comment by mmhamdy** [comment]
> Looks awesome! My guess is for a first try we want to shorten a bit + condense, and then in followups we can go more indepth (could be faster to iterate that way and not get hung up releasing everything completed)
> 
> What do you think?

Yeah, of course. This is going to get much shorter bit by bit. The plan is to grow the chapter (async) and then work on pruning. Releasing section by section will also make the process much easier.

**Comment by johko** [comment]
This really is an extensive outline, thanks for all the work, it looks awesome. I thought I know some stuff about ZSL, but I could not have come up with that much material :smile: 

Do you have any prioritization on which parts you want to work on first? In my opinion the _Zero-shot Learning methods_ part can have a little less priority for now as I think it is more important for people to see some actual applications as you will do in _Zero-shot Learning in Computer Vision_

**Comment by mmhamdy** [comment]
> Do you have any prioritization on which parts you want to work on first? In my opinion the Zero-shot Learning methods part can have a little less priority for now as I think it is more important for people to see some actual applications as you will do in Zero-shot Learning in Computer Vision

Yeah, we will take an inside-out approach and start from *Zero-shot Learning in Computer Vision* (which still needs an outline of its own, I think 😅) and then work on the rest of the sections once it is finished. The ZSL section will have its own share but we will keep it brief, kind of like introducing Q-Learning before talking about Deep Q-Learning in Reinforcement learning. The outermost chapters (Introduction, Advantages, Applications, and Frontiers) are mostly a couple of paragraphs long and won't take much of the chapter.

**Comment by merveenoyan** [comment]
@mmhamdy great outline! my only concern is that this is too broad and that you might find yourself overwhelmed in the process, so make sure to prioritize at first and we can iteratively release.

**Comment by mmhamdy** [comment]
> my only concern is that this is too broad and that you might find yourself overwhelmed in the process, so make sure to prioritize at first and we can iteratively release.

It's too broad, I agree. But a lot of the non-CV-specific content will be pruned and condensed to just provide a smooth transition from plain ZSL to CV ZSL. We are starting with the *Zero-shot Learning in Computer Vision* section in order not to get overwhelmed by the other sections. Once finished, we will branch out from there and start working on the rest of the sections.
