### ISSUE TITLE
Unit 2 - CNN | Transfer Learning/Fine-Tuning Draft Outline

### ISSUE THREAD

**Issue by alperenunlu** [johko/computer-vision-course#64]
Hey everyone.

This is the proposed sections for the Transfer Learning/Fine-Tuning Chapter.

## Transfer Learning/Fine-Tuning
* What is Transfer Learning?
* What is Fine-Tuning?
* Fine-Tuning with Torchvision [VGG16, ResNet50]
* Torchvision vs Timm
* Fine-Tuning with Timm [VGG16, ResNet50]
* Detailed Fine-Tuning tutorial on an image classification task. [Adapted on Different Models]

---

Open to suggestions for further improvement of the draft.

**Comment by johko** [comment]
hey, sorry for the late reply.

The outlien looks good to me :+1: 
I especially like that you bring TIMM into it and compare it with Torchvision

I also like the additions from @ATaylorAerospace , but maybe handle the points 
```
- The Role of Data in Transfer Learning (Explain how the quantity / quality of data affect Transfer Learning outcomes)
- Transfer Learning in Different Domains (Like object detection or segmentation domains)
```
as a bit lower priority for now. If you have time to cover it, cool. Else you can just shortly mention it without going into too much detail for now.

Any ideas on specific file structure, so what goes in an .mdx, what goes into notebooks?

**Comment by alperenunlu** [comment]
Hey @johko thank you for your comment.

> I especially like that you bring TIMM into it and compare it with Torchvision

Yeah `Timm` is somewhat hard for beginners but when you get used to it `Timm` becomes an incredible tool.

>Any ideas on specific file structure, so what goes in an .mdx, what goes into notebooks?

I am not fully familiar with new file structure but the sections on `TorchVision` and `Timm` are gonna be notebooks. Other sections can be `mdx` files.
